1 iteration
druzhininyury/yandex-workshop-event-service pull request #3
Opened 2024-11-21 09:31 UTC by DTF98

2024-11-21 12:32 UTC, druzhininyury requested changes
Имеются ошибки реализации. Нет юнит теста для сервиса. Не нашел файл с настройками Spring (например, application.properties).

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +public class EventController {
В контроллере (и соответственно в DTO) нет валидации данных. Они нужны.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/model/Event.java
> +    @EqualsAndHashCode.Include
Зачем эта аннотация, если ты не переопределяешь методы equals и hash?

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +    @Override
Методы, которые меняют базу данных, лучше явно оборачивать в транзакции.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Event not found"));
В Java есть уже нужное исключение: EntityNotFoundException.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/mapper/EventMapper.java
> +    EventResponse toDto(Event event);
Здесь лучше вообще не выводить поле createdDateTime, если оно null.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +    public List<EventResponse> getEvents(@RequestParam @Positive int page, @RequestParam @Positive int size,
Не реализован необязательный @RequestParam для ownerId.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +        if (requesterId != null) {
Поиск должен быть не по id запрашивающего пользователя, а по id владельца Event.

2024-11-21 12:32 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +            return eventRepository.findByOwnerId(requesterId, pageRequest).stream()
Проще так: .findByOwnerId(requesterId, pageRequest).getContent()

2024-11-21 12:32 UTC, druzhininyury commented on src/test/java/ru/practicum/workshop/eventservice/controller/EventControllerTest.java
> +public class EventControllerTest {
Нет тестов, которые бы проверяли валидность данных.

2024-11-21 12:32 UTC, druzhininyury commented on Event Service Tests.postman_collection.json
> +{
Тестов мало. Нет проверки исключительных случаев, например, удаление несуществующего события.

2024-11-22 21:10 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +public class EventController {
Какую именно валидацию ты имеешь ввиду? В задании я этого не видел...

2024-11-22 21:28 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Event not found"));
Это хорошо, конечно, но меня учили на практике создавать свои кастомные исключения на всё, это вопрос единообразия кода.

2024-11-22 21:47 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +            return eventRepository.findByOwnerId(requesterId, pageRequest).stream()
Не понял, мне тут надо еще мапить для локаничного перехода к дто... Зачем тут этот метод???

2024-11-23 02:09 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +public class EventController {
Базовые вещи. Непустота name, description, location, ownerId. Времена startDateTime и endDateTime должны быть в будущем и end должно быть позже start.

2024-11-23 02:10 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/eventservice/service/impl/EventServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Event not found"));
Хм, обычно учат переиспользовать код.

2024-11-23 09:34 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +public class EventController {
С последней валидацией затрудняюсь, я даже кастомную аннотацию такую не напишу, потому что оба поля динамические, придется в сервисе эту штуку обрабатывать костыльно.... Или у тебя есть идея как элегантно это сделать можно?

2024-11-23 09:40 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/eventservice/controller/EventController.java
> +public class EventController {
В Shareit было похожее с букингом, там мы этого не делали! Но если здесь по взрослому всё, то согласен что нужно, но тогда вопрос выше меня гложет!

2024-11-24 19:39 UTC, merged